### ISSUE TITLE
WordPress本番環境のOSは何を使用？

### ISSUE THREAD

**Issue by match5121** [team-itp/cms-proto#6]
WordPressのDockerイメージを作成するにあたり、
WordPressをデプロイする本番環境について確認したいです。
OSはLinux環境でしょうか。決まっていないならここで決めたいです。

**Comment by chameleonhead** [comment]
Azure の App Service だと一番安いプランは Windows になるので、Windows にしたいのですが、そのプランだとディスクサイズが 1GB しかないです。足りますか？
足りなければ、Linux でも Windows でも OK です。(多分一番安い構成の VM にすると思うので。)

**Comment by chameleonhead** [comment]
Linux VMで作成しました。完了したのでクローズします。
