### ISSUE TITLE
PDFの保存場所

### ISSUE THREAD

**Issue by match5121** [team-itp/cms-proto#9]
PDFはどこに保存しますか。
DBにBLOBで持つのでしょうか。

PDF EmbedderというプラグインでPDFの埋め込みはできましたが、
PDFファイルがwp-content/uploads/に保存されます。
これは問題でしょうか。

**Comment by chameleonhead** [comment]
Web サーバーは最小構成では 1GB しか容量がないので、問題になる可能性が高いです。DB に保存することは出来ないでしょうか。もしくは Azure のストレージで代用出来ませんか？
最悪の場合、WordPress も断念となりかねない問題です😰

**Comment by match5121** [comment]
DBの保存はできなさそうです。少なくとも新たにテーブルを作成する必要があると思います。

Azureのストレージを使用する方法はおそらくうまくいくと思います。
検証してみます。
無料アカウントでは１年しか使用できませんが、顧客に打診するということでよいでしょうか。

**Comment by chameleonhead** [comment]
調査ありがとうございます。ですが、バーチャルマシンについて調べたところそんなに高くないことがわかりました。あまり余計なことはせずに素直に VM を借りる方向に持っていきたいので、とりあえずこの件は #8 にまとめてクローズします。(問題なければ)

**Comment by chameleonhead** [comment]
と思ったのですが、Azure ストレージは相当安いみたいですね。どちらがいいでしょうか...。
